# services:
#   vector_db:
#     image: "qdrant/qdrant"
#     ports:
#       - "6333:6333"

# services:
#   vector_db:
#     image: qdrant/qdrant
#     ports:
#       - "6333:6333"
#     volumes:
#       - qdrant_storage:/qdrant/storage

#   backend:
#     build: ./backend
#     ports:
#       - "8000:8000"
#     environment:
#       - OPENAI_API_KEY=${OPENAI_API_KEY}
#       - QDRANT_URL=http://vector_db:6333
#     depends_on:
#       - vector_db

# volumes:
#   qdrant_storage:
services:
  vector_db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  backend:
    build: ./backend
    container_name: my_rag_backend
    ports:
      - "8000:8000"
    # environment:
    #   - OPENAI_API_KEY=${OPENAI_API_KEY}
    #   - QDRANT_URL=http://vector_db:6333
    env_file:
      - .env
    depends_on:
      - vector_db

volumes:
  qdrant_storage:
